root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/app ./cmd/server"
bin = "tmp/app"
full_bin = "APP_ENV=dev ./tmp/app"

include_ext = ["go"]
exclude_dir = ["tmp", "vendor", "docs"]
exclude_file = []
exclude_regex = ["_test.go"]

delay = 1000
stop_on_error = true
log = "build-errors.log"

[log]
time = true

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"
